### ISSUE TITLE
im not on there

### ISSUE THREAD

**Issue by XenonOrSomething** [larsl2005/GorillaTagModerators#3]
massive issue

**Comment by Chin0303** [comment]
attention seeking at its finest

**Comment by Chin0303** [comment]
> I have no clue how people are even finding this repo. I'm gonna stop merging/adding people for the memes, I did it twice, thats enough. I have no clue why people even want to be on here.

die lofiat had het gevonden, daarna wouden alle "modders" die aandachts problemen hebben er ook op. Ze denken altijd dat ze heel wat zijn, maar ze doen eigenlijk nooit iets nuttigs. Het is puur voor aandacht zodat ze dit kunnen laten zien aan anderen en doen alsof ze speciaal ofz zijn.
